# Chapter 3 - It starts with a tensor

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a

[1.0, 2.0, 1.0]

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
points = torch.zeros(6)
points[0] = 4.0
points

tensor([4., 0., 0., 0., 0., 0.])

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0]])
points

tensor([[4., 1.],
        [5., 3.]])

In [13]:
points.shape

torch.Size([2, 2])

In [14]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points[0]

tensor([0., 0.])

In [16]:
points[0,1]

tensor(0.)

In [17]:
points[None]

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [21]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[ 0.7118, -1.7827,  0.5782, -1.0941, -0.3815],
         [ 1.7140,  1.8611, -1.3996, -0.6850, -1.6758],
         [-1.0196,  1.1004,  0.7069, -0.1086,  0.1063],
         [-0.5252, -0.0879, -0.3185, -0.6734, -0.6974],
         [ 1.9827,  0.2078, -1.2448,  1.5740, -0.7236]],

        [[ 0.2616,  1.3537, -0.8112, -1.0487, -0.7729],
         [ 0.7701,  0.0153, -1.6063,  1.4773,  0.5029],
         [ 0.1838, -0.1038,  0.2215, -0.0626,  0.0652],
         [ 0.2909,  0.3312, -0.2465,  0.9073,  1.4851],
         [-1.8758, -0.1947,  1.3782,  0.7178,  1.6530]],

        [[-1.0569, -0.7104, -0.0509, -1.1360,  1.9622],
         [ 0.9560, -1.1361,  0.8826, -0.5345, -0.2223],
         [ 0.6226,  2.8174, -0.3696,  0.6384,  0.4291],
         [-0.9983,  1.2298,  1.1995, -0.7038,  1.2312],
         [ 0.1553, -0.6849,  0.5522,  0.1624, -1.5266]]])

In [22]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [19]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [20]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[-0.8588, -0.4921, -0.9000,  1.1259, -0.3316],
        [-0.9568, -1.0246, -0.3826,  0.0430,  0.0632],
        [ 0.4541, -0.9963,  0.4895,  0.1454,  0.0865],
        [ 1.2966,  0.4817, -0.0904, -0.3266,  0.3703],
        [-0.4602, -0.0911, -0.2188,  0.5265, -0.2282]])

In [23]:
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [24]:
double_points = torch.ones(10, 2, dtype = torch.double)
short_points = torch.tensor([[1,2],[3,4]], dtype = torch.short)

In [ ]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [26]:
double_points.dtype

torch.float64

In [27]:
short_points.dtype

torch.int16

In [28]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype = torch.short)

In [29]:
double_points = torch.zeros(10,2).to(torch.short)

In [30]:
double_points

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)